version: '2'
services:
    bluesource-app:
        image: bluesource
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bluesource-postgresql:5432/bluesource
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bluesource-elasticsearch:9300
        ports:
            - 8080:8080
    bluesource-postgresql:
        extends:
            file: postgresql.yml
            service: bluesource-postgresql
    bluesource-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bluesource-elasticsearch
